import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAvatarUrlAndSchemaSync1773287140782 implements MigrationInterface {
    name = 'AddAvatarUrlAndSchemaSync1773287140782'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` DROP FOREIGN KEY \`FK_employee_schedule_employee\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP FOREIGN KEY \`FK_aaf6cdeebd8497289338899961b\``);
        await queryRunner.query(`DROP INDEX \`IDX_schedule_day_of_week\` ON \`employee_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_schedule_is_day_off\` ON \`employee_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_schedule_specific_date\` ON \`employee_schedules\``);
        await queryRunner.query(`DROP INDEX \`UQ_employee_day_date\` ON \`employee_schedules\``);
        await queryRunner.query(`CREATE TABLE \`testimonials\` (\`id\` varchar(36) NOT NULL, \`customerName\` varchar(100) NOT NULL, \`customerTitle\` varchar(255) NULL, \`avatarUrl\` varchar(255) NULL, \`content\` text NOT NULL, \`rating\` int NOT NULL DEFAULT '5', \`isActive\` tinyint NOT NULL DEFAULT 1, \`displayOrder\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promotions\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(200) NOT NULL, \`description\` text NULL, \`discountType\` varchar(20) NOT NULL DEFAULT 'percent', \`discountValue\` decimal(10,2) NULL, \`badge\` varchar(50) NULL, \`imageUrl\` varchar(255) NULL, \`validFrom\` date NULL, \`validUntil\` date NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`displayOrder\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`media_files\` (\`id\` varchar(36) NOT NULL, \`filename\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`mimeType\` varchar(100) NOT NULL, \`size\` int NOT NULL, \`url\` varchar(500) NOT NULL, \`uploadedById\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contact_messages\` (\`id\` varchar(36) NOT NULL, \`fullName\` varchar(100) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(20) NULL, \`subject\` varchar(200) NOT NULL, \`message\` text NOT NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_categories\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(100) NOT NULL, \`slug\` varchar(100) NOT NULL, \`description\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_903a6ea496e83ba9bec10af583\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_comments\` (\`id\` varchar(36) NOT NULL, \`postId\` varchar(255) NOT NULL, \`parentId\` varchar(255) NULL, \`authorName\` varchar(100) NOT NULL, \`authorEmail\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`isApproved\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_tags\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(50) NOT NULL, \`slug\` varchar(50) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_afc33ebb304bb6ee9dc0a26c5d\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_post_categories\` (\`postId\` varchar(36) NOT NULL, \`categoryId\` varchar(36) NOT NULL, INDEX \`IDX_f5716f3191cc27d08a7bf6d078\` (\`postId\`), INDEX \`IDX_435cbf292acb4f419f059b3efe\` (\`categoryId\`), PRIMARY KEY (\`postId\`, \`categoryId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_post_tags\` (\`postId\` varchar(36) NOT NULL, \`tagId\` varchar(36) NOT NULL, INDEX \`IDX_ad4d63c771dcd9365fe4fe5a46\` (\`postId\`), INDEX \`IDX_d6e4bd52e7bf4bd69be040cb17\` (\`tagId\`), PRIMARY KEY (\`postId\`, \`tagId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`time_slots\` DROP COLUMN \`currentBookings\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`featuredImage\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`metaKeywords\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`categoryId\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`allowComments\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`password\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`role\` varchar(255) NOT NULL DEFAULT 'customer'`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`employees\` ADD \`avatarUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`admins\` ADD \`role\` varchar(20) NOT NULL DEFAULT 'admin'`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`thumbnailUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`scheduledAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`isFeatured\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD UNIQUE INDEX \`IDX_88acd889fbe17d0e16cc4bc917\` (\`phone\`)`);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` DROP COLUMN \`employeeId\``);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` ADD \`employeeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`title\` varchar(500) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_5b2818a2c45c3edb9991b1c7a5\` ON \`blog_posts\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`slug\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD UNIQUE INDEX \`IDX_5b2818a2c45c3edb9991b1c7a5\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`metaTitle\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`metaTitle\` varchar(200) NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`metaDescription\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`metaDescription\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` CHANGE \`status\` \`status\` enum ('draft', 'published', 'scheduled') NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` CHANGE \`readingTime\` \`readingTime\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`authorId\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`authorId\` varchar(255) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_89adc856efd9b50f0c35b8136b\` ON \`employee_schedules\` (\`employeeId\`, \`dayOfWeek\`, \`specificDate\`)`);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` ADD CONSTRAINT \`FK_4d5b29c922b0411a2a6c9e7c206\` FOREIGN KEY (\`employeeId\`) REFERENCES \`employees\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`media_files\` ADD CONSTRAINT \`FK_569e22d0659fcfc4d2ddf7e5271\` FOREIGN KEY (\`uploadedById\`) REFERENCES \`admins\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_comments\` ADD CONSTRAINT \`FK_0a190c1025d773ec5ca2c039c92\` FOREIGN KEY (\`postId\`) REFERENCES \`blog_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_comments\` ADD CONSTRAINT \`FK_02b996a30d6a7a934ef71d97739\` FOREIGN KEY (\`parentId\`) REFERENCES \`blog_comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD CONSTRAINT \`FK_09269227c7acf3cdf47ea4051e1\` FOREIGN KEY (\`authorId\`) REFERENCES \`admins\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_post_categories\` ADD CONSTRAINT \`FK_f5716f3191cc27d08a7bf6d0781\` FOREIGN KEY (\`postId\`) REFERENCES \`blog_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`blog_post_categories\` ADD CONSTRAINT \`FK_435cbf292acb4f419f059b3efea\` FOREIGN KEY (\`categoryId\`) REFERENCES \`blog_categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` ADD CONSTRAINT \`FK_ad4d63c771dcd9365fe4fe5a463\` FOREIGN KEY (\`postId\`) REFERENCES \`blog_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` ADD CONSTRAINT \`FK_d6e4bd52e7bf4bd69be040cb17d\` FOREIGN KEY (\`tagId\`) REFERENCES \`blog_tags\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` DROP FOREIGN KEY \`FK_d6e4bd52e7bf4bd69be040cb17d\``);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` DROP FOREIGN KEY \`FK_ad4d63c771dcd9365fe4fe5a463\``);
        await queryRunner.query(`ALTER TABLE \`blog_post_categories\` DROP FOREIGN KEY \`FK_435cbf292acb4f419f059b3efea\``);
        await queryRunner.query(`ALTER TABLE \`blog_post_categories\` DROP FOREIGN KEY \`FK_f5716f3191cc27d08a7bf6d0781\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP FOREIGN KEY \`FK_09269227c7acf3cdf47ea4051e1\``);
        await queryRunner.query(`ALTER TABLE \`blog_comments\` DROP FOREIGN KEY \`FK_02b996a30d6a7a934ef71d97739\``);
        await queryRunner.query(`ALTER TABLE \`blog_comments\` DROP FOREIGN KEY \`FK_0a190c1025d773ec5ca2c039c92\``);
        await queryRunner.query(`ALTER TABLE \`media_files\` DROP FOREIGN KEY \`FK_569e22d0659fcfc4d2ddf7e5271\``);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` DROP FOREIGN KEY \`FK_4d5b29c922b0411a2a6c9e7c206\``);
        await queryRunner.query(`DROP INDEX \`IDX_89adc856efd9b50f0c35b8136b\` ON \`employee_schedules\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`authorId\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`authorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` CHANGE \`readingTime\` \`readingTime\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` CHANGE \`status\` \`status\` enum ('draft', 'published', 'archived') NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`metaDescription\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`metaDescription\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`metaTitle\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`metaTitle\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP INDEX \`IDX_5b2818a2c45c3edb9991b1c7a5\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_5b2818a2c45c3edb9991b1c7a5\` ON \`blog_posts\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` DROP COLUMN \`employeeId\``);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` ADD \`employeeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP INDEX \`IDX_88acd889fbe17d0e16cc4bc917\``);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`email\` \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`isFeatured\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`scheduledAt\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP COLUMN \`thumbnailUrl\``);
        await queryRunner.query(`ALTER TABLE \`admins\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`employees\` DROP COLUMN \`avatarUrl\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`isActive\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`allowComments\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`categoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`metaKeywords\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD \`featuredImage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`time_slots\` ADD \`currentBookings\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX \`IDX_d6e4bd52e7bf4bd69be040cb17\` ON \`blog_post_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_ad4d63c771dcd9365fe4fe5a46\` ON \`blog_post_tags\``);
        await queryRunner.query(`DROP TABLE \`blog_post_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_435cbf292acb4f419f059b3efe\` ON \`blog_post_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_f5716f3191cc27d08a7bf6d078\` ON \`blog_post_categories\``);
        await queryRunner.query(`DROP TABLE \`blog_post_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_afc33ebb304bb6ee9dc0a26c5d\` ON \`blog_tags\``);
        await queryRunner.query(`DROP TABLE \`blog_tags\``);
        await queryRunner.query(`DROP TABLE \`blog_comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_903a6ea496e83ba9bec10af583\` ON \`blog_categories\``);
        await queryRunner.query(`DROP TABLE \`blog_categories\``);
        await queryRunner.query(`DROP TABLE \`contact_messages\``);
        await queryRunner.query(`DROP TABLE \`media_files\``);
        await queryRunner.query(`DROP TABLE \`promotions\``);
        await queryRunner.query(`DROP TABLE \`testimonials\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_employee_day_date\` ON \`employee_schedules\` (\`employeeId\`, \`dayOfWeek\`, \`specificDate\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_schedule_specific_date\` ON \`employee_schedules\` (\`specificDate\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_schedule_is_day_off\` ON \`employee_schedules\` (\`isDayOff\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_schedule_day_of_week\` ON \`employee_schedules\` (\`dayOfWeek\`)`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD CONSTRAINT \`FK_aaf6cdeebd8497289338899961b\` FOREIGN KEY (\`categoryId\`) REFERENCES \`content_categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`employee_schedules\` ADD CONSTRAINT \`FK_employee_schedule_employee\` FOREIGN KEY (\`employeeId\`) REFERENCES \`employees\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
