import { SxProps, Theme } from "@mui/material";

export const pricingStyles = {
  container: {
    py: { xs: 8, md: 12 },
    backgroundColor: "white",
    position: "relative",
  },
  header: {
    textAlign: "center",
    maxWidth: "800px",
    mx: "auto",
    mb: { xs: 5, md: 8 },
  },
  overline: {
    fontSize: "0.75rem",
    letterSpacing: "4px",
    color: "primary.main",
    fontWeight: 600,
    display: "block",
    mb: 2,
    textTransform: "uppercase",
  },
  title: {
    fontSize: { xs: "2.25rem", md: "3.5rem", lg: "4rem" },
    fontWeight: 300,
    mb: 3,
    color: "text.primary",
    fontFamily: '"Playfair Display", serif',
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
  },
  description: {
    fontSize: { xs: "1rem", md: "1.125rem" },
    lineHeight: 1.8,
    color: "text.secondary",
  },
  card: {
    height: "100%",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    overflow: "hidden",
    borderRadius: 3,
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    position: "relative",
    backgroundColor: "white",
    "&:hover": {
      transform: "translateY(-12px)",
      boxShadow: "0 16px 48px rgba(0, 0, 0, 0.15)",
      "& $image": {
        transform: "scale(1.1)",
      },
      "& $cardContent": {
        backgroundColor: "#fafafa",
      },
    },
  },
  image: {
    objectFit: "cover",
    transition: "transform 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
    width: "100%",
    height: "250px",
    display: "block",
  },
  cardContent: {
    p: 3,
    transition: "background-color 0.4s ease",
  },
  price: {
    color: "primary.main",
    fontWeight: 600,
    mt: 1,
    fontSize: "1.5rem",
    fontFamily: '"Playfair Display", serif',
  },
  categoryTitle: {
    fontSize: { xs: "1.75rem", md: "2.25rem" },
    fontWeight: 400,
    mb: 3,
    color: "text.primary",
    fontFamily: '"Playfair Display", serif',
    position: "relative",
    "&::after": {
      content: '""',
      position: "absolute",
      bottom: -8,
      left: 0,
      width: "60px",
      height: "2px",
      backgroundColor: "primary.main",
    },
  },
  featuredContainer: {
    py: { xs: 10, md: 14 },
    position: "relative",
    background:
      "linear-gradient(135deg, #fafafa 0%, #ffffff 50%, #f5f5f5 100%)",
    overflow: "hidden",
  },
  backgroundPattern: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.03,
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
    zIndex: 0,
  },
  featuredTitle: {
    fontSize: { xs: "2.5rem", md: "3.5rem", lg: "4rem" },
    fontWeight: 400,
    mb: 3,
    color: "text.primary",
    fontFamily: '"Playfair Display", serif',
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
    position: "relative",
    zIndex: 1,
  },
  featuredCard: {
    height: "100%",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    overflow: "visible",
    borderRadius: 4,
    boxShadow: "0 8px 30px rgba(0, 0, 0, 0.08)",
    position: "relative",
    backgroundColor: "white",
    border: "2px solid transparent",
    zIndex: 1,
    "&:hover": {
      transform: "translateY(-8px)",
      boxShadow: "0 20px 60px rgba(212, 175, 140, 0.2)",
      borderColor: "primary.light",
    },
  },
  featuredCardHighlight: {
    border: "3px solid",
    borderColor: "primary.main",
    boxShadow: "0 12px 40px rgba(212, 175, 140, 0.25)",
    transform: "scale(1.05)",
    zIndex: 2,
    "&:hover": {
      transform: "scale(1.08) translateY(-8px)",
      boxShadow: "0 24px 70px rgba(212, 175, 140, 0.35)",
    },
  },
  featuredBadge: {
    position: "absolute",
    top: -12,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    backgroundColor: "primary.main",
    color: "white",
    px: 2,
    py: 0.5,
    borderRadius: 2,
    boxShadow: "0 4px 12px rgba(212, 175, 140, 0.4)",
    zIndex: 3,
  },
  featuredCardContent: {
    p: 4,
    position: "relative",
    zIndex: 1,
  },
  featuredPrice: {
    fontWeight: 700,
    fontFamily: '"Playfair Display", serif',
    lineHeight: 1,
  },
} satisfies Record<string, SxProps<Theme>>;
