import { SxProps, Theme } from '@mui/material'

export const wellnessStyles: Record<string, SxProps<Theme>> = {
  container: {
    position: 'relative',
    py: { xs: 8, md: 12 },
    backgroundColor: '#fafafa',
    overflow: 'hidden',
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundImage: 'url(https://picsum.photos/1920/1080?random=4)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    opacity: 0.08,
    zIndex: 0,
    filter: 'blur(1px)',
  },
  containerInner: {
    position: 'relative',
    zIndex: 1,
  },
  overline: {
    fontSize: '0.75rem',
    letterSpacing: '4px',
    color: 'primary.main',
    fontWeight: 600,
    display: 'block',
    mb: 2,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: { xs: '2.25rem', md: '3.5rem', lg: '4rem' },
    fontWeight: 300,
    mb: 3,
    color: 'text.primary',
    fontFamily: '"Playfair Display", serif',
    lineHeight: 1.2,
    letterSpacing: '-0.02em',
  },
  description: {
    fontSize: { xs: '1rem', md: '1.125rem' },
    lineHeight: 1.8,
    color: 'text.secondary',
    mb: 4,
    maxWidth: '90%',
  },
  button: {
    backgroundColor: 'primary.main',
    color: 'white',
    px: { xs: 4, md: 5 },
    py: { xs: 1.5, md: 1.75 },
    fontSize: { xs: '14px', md: '15px' },
    borderRadius: 2,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      backgroundColor: 'primary.dark',
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 20px rgba(212, 175, 140, 0.4)',
    },
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: { xs: '400px', md: '600px' },
    overflow: 'hidden',
    borderRadius: 3,
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.12)',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      transform: 'scale(1.02)',
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.18)',
    },
  },
  image: {
    position: 'relative',
    width: '100%',
    height: '100%',
    borderRadius: 3,
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '-50px',
      right: 'calc(50px + 45px)',
      height: 'calc(100% + 2 * 50px)',
      width: '68.6%',
      backgroundColor: 'primary.light',
      zIndex: 1,
      opacity: 0.3,
      transition: 'opacity 0.4s ease',
    },
    '&:hover::before': {
      opacity: 0.2,
    },
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      transition: 'transform 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
      position: 'relative',
      zIndex: 2,
    },
    '&:hover img': {
      transform: 'scale(1.05)',
    },
  },
  dandelionSeed: {
    position: 'absolute',
    top: { xs: 20, md: 30 },
    left: { xs: 20, md: 30 },
    zIndex: 2,
  },
  decorativeBowl: {
    position: 'absolute',
    top: { xs: 60, md: 80 },
    left: { xs: 20, md: 30 },
    zIndex: 2,
    width: { xs: 60, md: 80 },
    height: { xs: 60, md: 80 },
    borderRadius: '50%',
    backgroundColor: '#8b6f47',
    border: '3px solid #6b5535',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: 4,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '20%',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '60%',
      height: '60%',
      borderRadius: '50%',
      backgroundColor: '#2d5a3d',
      opacity: 0.8,
    },
  },
}

