import { SxProps, Theme } from '@mui/material'

export const workingHoursStyles: Record<string, SxProps<Theme>> = {
  container: {
    py: 10,
    backgroundColor: 'white',
  },
  gridContainer: {
    position: 'relative',
    minHeight: '600px',
    alignItems: 'center',
  },
  leftBoxGrid: {
    position: 'relative',
    zIndex: 3,
    display: 'flex',
    justifyContent: 'flex-end',
    pr: { xs: 0, md: -4 },
    mt: { xs: 0, md: 0 },
    mb: { xs: 2, md: 0 },
    alignSelf: 'center',
  },
  rightBoxGrid: {
    position: 'relative',
    zIndex: 3,
    display: 'flex',
    justifyContent: 'flex-start',
    pl: { xs: 0, md: -4 },
    mt: { xs: 2, md: 0 },
    alignSelf: 'center',
  },
  imageGrid: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    px: { xs: 0, md: 0 },
  },
  leftBox: {
    backgroundColor: 'white',
    p: { xs: 3, md: 4 },
    borderRadius: 3,
    maxWidth: '100%',
    position: 'relative',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.12)',
    zIndex: 3,
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    backgroundImage: 'url("data:image/svg+xml,%3Csvg width=\'100\' height=\'100\' viewBox=\'0 0 100 100\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M50 50m-30 0a30 30 0 1 1 60 0a30 30 0 1 1 -60 0\' fill=\'none\' stroke=\'%23e8e8e8\' stroke-width=\'0.5\' opacity=\'0.4\'/%3E%3Cpath d=\'M50 50m-20 0a20 20 0 1 1 40 0a20 20 0 1 1 -40 0\' fill=\'none\' stroke=\'%23e8e8e8\' stroke-width=\'0.5\' opacity=\'0.3\'/%3E%3Cpath d=\'M50 50m-10 0a10 10 0 1 1 20 0a10 10 0 1 1 -20 0\' fill=\'none\' stroke=\'%23e8e8e8\' stroke-width=\'0.5\' opacity=\'0.2\'/%3E%3C/svg%3E")',
    backgroundSize: '200px 200px',
    backgroundPosition: 'center',
    backgroundRepeat: 'repeat',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.18)',
    },
  },
  rightBox: {
    backgroundColor: '#4ecdc4', // Teal color
    p: { xs: 3, md: 4 },
    borderRadius: 3,
    maxWidth: '100%',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: { xs: '300px', md: '450px' },
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.12)',
    position: 'relative',
    zIndex: 3,
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 12px 40px rgba(78, 205, 196, 0.3)',
    },
  },
  openHoursTitle: {
    fontWeight: 700,
    fontSize: { xs: '1.5rem', md: '1.75rem' },
    color: '#333333',
    mb: 2.5,
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  welcomeText: {
    color: '#666666',
    fontSize: '0.9rem',
    lineHeight: 1.7,
    mb: 3,
  },
  hoursList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  hourItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    backgroundColor: '#ff6b6b', // Reddish-orange
    flexShrink: 0,
  },
  hourText: {
    color: '#333333',
    fontSize: '0.9rem',
    '& strong': {
      fontWeight: 600,
      color: '#333333',
    },
  },
  centerImage: {
    width: '100%',
    maxWidth: '500px',
    height: 'auto',
    minHeight: { xs: '400px', md: '600px' },
    objectFit: 'cover',
    borderRadius: 3,
    position: 'relative',
    zIndex: 1,
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.12)',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      transform: 'scale(1.02)',
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.18)',
    },
  },
  relaxTitle: {
    fontWeight: 700,
    fontSize: { xs: '1.5rem', md: '1.75rem' },
    color: 'white',
    mb: 2.5,
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  relaxText: {
    color: 'rgba(255, 255, 255, 0.95)',
    fontSize: '0.9rem',
    lineHeight: 1.7,
    mb: 4,
    textAlign: 'center',
    px: 1,
  },
  aboutButton: {
    borderColor: 'white',
    color: 'white',
    px: 4,
    py: 1.5,
    fontSize: '0.9rem',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '1px',
    borderRadius: 2,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      borderColor: 'white',
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 20px rgba(255, 255, 255, 0.3)',
    },
  },
}
