import { DataSource } from 'typeorm';
import { Service } from '../../entities/service.entity';

/**
 * SEED-001: Service Price Update
 * Cập nhật toàn bộ bảng giá dịch vụ theo menu mới nhất (2026)
 *
 * Thay đổi chính:
 * - Thêm 7 dịch vụ Chăm Sóc Da mới (Thanh Lọc Da, Lấy Nhân Mụn x3, Thải Độc CO2, Peel Da, Cấy Trắng Nano)
 * - Giữ lại Chăm Sóc Da 349k (version cũ)
 * - Cập nhật bảng giá Triệt Lông (11 vùng, buổi lẻ + gói 10 lần)
 * - Cập nhật steps cho 4 combo Gội Đầu Dưỡng Sinh
 * - Cập nhật Design (10 dịch vụ nail art)
 * - Cập nhật Eye Lash (12 dịch vụ)
 * - Cập nhật Dịch Vụ Da (giữ nguyên 3 dịch vụ 200k)
 * - Cập nhật Dịch Vụ Lẻ (14 dịch vụ, Massage body 3 mức giá)
 * - Bỏ Nail - Gel Polish và Nail Extension
 */
export const seedServicePriceUpdate = async (dataSource: DataSource): Promise<void> => {
  console.log('\n📋 [seed-001] Bắt đầu cập nhật bảng giá dịch vụ...');

  const serviceRepo = dataSource.getRepository(Service);

  // ─────────────────────────────────────────────────────────────────────────
  // STEP 1: Soft-delete toàn bộ services cũ (set isActive = false)
  // Không hard-delete vì bảng bookings có FK tham chiếu service.id
  // ─────────────────────────────────────────────────────────────────────────
  const categoriesToDeactivate = [
    'Design',
    'Eye Lash',
    'Gội Đầu Dưỡng Sinh',
    'Chăm Sóc Da',
    'Dịch Vụ Da',
    'Dịch Vụ Lẻ',
    'Triệt Lông',
    'Nail - Gel Polish',
    'Nail - Filling & Extension',
  ];

  for (const cat of categoriesToDeactivate) {
    const existing = await serviceRepo.find({ where: { category: cat } });
    if (existing.length > 0) {
      await serviceRepo.save(existing.map((s) => ({ ...s, isActive: false })));
      console.log(`  ⏸️  Đã deactivate ${existing.length} record(s) category: ${cat}`);
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // STEP 2: Seed data mới
  // ─────────────────────────────────────────────────────────────────────────
  const newServices: Partial<Service>[] = [

    // ════════════════════════════════════════════════════════
    // CHĂM SÓC DA — 8 dịch vụ (7 mới + 1 cũ giữ lại)
    // ════════════════════════════════════════════════════════
    {
      name: 'Chăm Sóc Da',
      description: 'Liệu trình chăm sóc da mặt toàn diện 13 bước, làm sạch sâu và dưỡng da.',
      singlePrice: 349000,
      priceType: 'single',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Chăm Sóc Da',
      stepsCount: 13,
      steps: [
        'Tẩy trang rửa mặt',
        'Tẩy tế bào chết da',
        'Xông hơi',
        'Massage mặt',
        'Hút bã nhờn, dầu',
        'Sát khuẩn',
        'Lấy Mụn',
        'Thoa nước hoa hồng',
        'Làm sạch',
        'Massage cổ',
        'Đi bùa nóng, lạnh',
        'Đắp mặt nạ',
        'Điện di',
      ],
      isActive: true,
    },
    {
      name: 'Thanh Lọc Da',
      description: 'Liệu trình thanh lọc da chuyên sâu 12 bước, kết hợp Aqua Peel và chiếu đèn sinh học.',
      singlePrice: 250000,
      priceType: 'single',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Chăm Sóc Da',
      stepsCount: 12,
      steps: [
        'Soi da',
        'Tẩy trang',
        'Tẩy tế bào chết da',
        'Massage mặt nâng cơ',
        'Xông hơi + cạo sửi',
        'Hút bã nhờn',
        'Aqua Peel',
        'Đắp mask',
        'Chiếu đèn sinh học',
        'Massage đầu',
        'Thoa serum',
        'Điện di',
      ],
      isActive: true,
    },
    {
      name: 'Lấy Nhân Mụn Cơ Bản',
      description: 'Liệu trình lấy nhân mụn cơ bản 13 bước, làm sạch và sát khuẩn da chuyên nghiệp.',
      singlePrice: 200000,
      priceType: 'single',
      duration: '50 phút',
      durationMinutes: 50,
      category: 'Chăm Sóc Da',
      stepsCount: 13,
      steps: [
        'Soi da',
        'Tẩy trang',
        'Rửa mặt',
        'Tẩy tế bào chết da',
        'Massage mặt',
        'Xông hơi + cạo sửi',
        'Hút bã nhờn',
        'Sát khuẩn lần 1',
        'Lấy nhân mụn',
        'Sát khuẩn lần 2',
        'Điện tim',
        'Đắp mặt nạ + chiếu đèn sinh học',
        'Massage đầu',
      ],
      isActive: true,
    },
    {
      name: 'Lấy Nhân Mụn Cấp Độ 2',
      description: 'Liệu trình lấy nhân mụn cấp độ 2 gồm 14 bước, bổ sung bước ủ mụn chuyên sâu hơn.',
      singlePrice: 250000,
      priceType: 'single',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Chăm Sóc Da',
      stepsCount: 14,
      steps: [
        'Soi da',
        'Tẩy trang',
        'Rửa mặt',
        'Tẩy tế bào chết da',
        'Massage mặt',
        'Xông hơi + cạo sửi',
        'Ủ mụn',
        'Hút bã nhờn',
        'Sát khuẩn lần 1',
        'Lấy nhân mụn',
        'Sát khuẩn lần 2',
        'Điện tim',
        'Đắp mặt nạ + chiếu đèn sinh học',
        'Massage đầu',
      ],
      isActive: true,
    },
    {
      name: 'Lấy Nhân Mụn Chuyên Sâu',
      description: 'Liệu trình lấy nhân mụn chuyên sâu 16 bước, bao gồm bùa nóng lạnh và dị tình chất.',
      singlePrice: 350000,
      priceType: 'single',
      duration: '75 phút',
      durationMinutes: 75,
      category: 'Chăm Sóc Da',
      stepsCount: 16,
      steps: [
        'Soi da',
        'Tẩy trang',
        'Rửa mặt',
        'Tẩy tế bào chết da',
        'Massage mặt',
        'Xông hơi + cạo sửi',
        'Ủ mụn',
        'Hút bã nhờn',
        'Sát khuẩn lần 1',
        'Lấy nhân mụn',
        'Sát khuẩn lần 2',
        'Điện tim',
        'Đắp mặt nạ + chiếu đèn sinh học',
        'Bùa nóng lạnh',
        'Dị tình chất',
        'Massage đầu',
      ],
      isActive: true,
    },
    {
      name: 'Thải Độc CO2',
      description: 'Liệu trình thải độc CO2 cao cấp 18 bước, làm sáng da và cung cấp dưỡng chất sâu.',
      singlePrice: 550000,
      priceType: 'single',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Chăm Sóc Da',
      stepsCount: 18,
      steps: [
        'Soi da',
        'Tẩy trang',
        'Rửa mặt',
        'Tẩy tế bào chết da',
        'Massage mặt',
        'Xông hơi + cạo sửi',
        'Hút bã nhờn',
        'Sát khuẩn lần 1',
        'Lấy nhân mụn (Nếu có)',
        'Sát khuẩn lần 2',
        'Điện tim',
        'Thải độc CO2',
        'Chiếu đèn sinh học',
        'Massage đầu',
        'Đắp mask',
        'Thoa serum',
        'Điện di',
        'Thoa kem chống nắng',
      ],
      isActive: true,
    },
    {
      name: 'Peel Da',
      description: 'Liệu trình peel da 12 bước, loại bỏ tế bào chết và tái tạo da hiệu quả.',
      singlePrice: 590000,
      priceType: 'single',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Chăm Sóc Da',
      stepsCount: 12,
      steps: [
        'Soi da',
        'Tẩy trang',
        'Rửa mặt',
        'Tẩy tế bào chết da',
        'Xông hơi + cạo sửi',
        'Hút bã nhờn',
        'Sát khuẩn lần 1',
        'Ủ mụn',
        'Sát khuẩn lần 2',
        'Điện tim',
        'Peel da',
        'Điện di',
      ],
      isActive: true,
    },
    {
      name: 'Cấy Trắng Nano',
      description: 'Liệu trình cấy trắng Nano 13 bước bằng máy DorterPen, giúp da sáng mịn và đều màu.',
      singlePrice: 350000,
      priceType: 'single',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Chăm Sóc Da',
      stepsCount: 13,
      steps: [
        'Tẩy trang',
        'Rửa mặt',
        'Tẩy tế bào chết da',
        'Massage mặt',
        'Xông hơi + cạo sửi',
        'Phun Ionner',
        'Cấy trắng bằng máy DorterPen',
        'Chiếu ánh sáng',
        'Đắp mask',
        'Massage đầu',
        'Thoa serum',
        'Điện di',
        'Thoa kem chống nắng',
      ],
      isActive: true,
    },

    // ════════════════════════════════════════════════════════
    // TRIỆT LÔNG — 11 vùng (buổi lẻ + gói 10 lần)
    // ════════════════════════════════════════════════════════
    {
      name: 'Triệt Lông',
      zone: 'Nách',
      description: 'Triệt lông vùng nách bằng công nghệ hiện đại, an toàn và hiệu quả.',
      singlePrice: 129000,
      packagePrice: 899000,
      packageSessions: 10,
      priceType: 'package',
      duration: '20 phút',
      durationMinutes: 20,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Mép',
      description: 'Triệt lông vùng mép (ria mép), giúp da mặt mịn màng và tự tin hơn.',
      singlePrice: 129000,
      packagePrice: 899000,
      packageSessions: 10,
      priceType: 'package',
      duration: '20 phút',
      durationMinutes: 20,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Mặt',
      description: 'Triệt lông toàn mặt, cho da mặt sáng mịn và đều màu.',
      singlePrice: 179000,
      packagePrice: 1799000,
      packageSessions: 10,
      priceType: 'package',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Bụng',
      description: 'Triệt lông vùng bụng, giúp làn da vùng bụng mịn màng.',
      singlePrice: 79000,
      packagePrice: 1399000,
      packageSessions: 10,
      priceType: 'package',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Lưng',
      description: 'Triệt lông toàn vùng lưng, phù hợp cho cả nam và nữ.',
      singlePrice: 349000,
      packagePrice: 2799000,
      packageSessions: 10,
      priceType: 'package',
      duration: '40 phút',
      durationMinutes: 40,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Bikini',
      description: 'Triệt lông vùng bikini an toàn và hiệu quả.',
      singlePrice: 349000,
      packagePrice: 2799000,
      packageSessions: 10,
      priceType: 'package',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: '1/2 Tay',
      description: 'Triệt lông nửa tay (từ cổ tay đến khuỷu tay hoặc khuỷu tay đến vai).',
      singlePrice: 290000,
      packagePrice: 2199000,
      packageSessions: 10,
      priceType: 'package',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Full Tay',
      description: 'Triệt lông toàn bộ tay từ vai đến cổ tay.',
      singlePrice: 390000,
      packagePrice: 3199000,
      packageSessions: 10,
      priceType: 'package',
      duration: '50 phút',
      durationMinutes: 50,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: '1/2 Chân',
      description: 'Triệt lông nửa chân (từ đầu gối trở xuống hoặc từ đùi đến đầu gối).',
      singlePrice: 349000,
      packagePrice: 2799000,
      packageSessions: 10,
      priceType: 'package',
      duration: '40 phút',
      durationMinutes: 40,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Full Chân',
      description: 'Triệt lông toàn bộ chân từ hông đến cổ chân.',
      singlePrice: 449000,
      packagePrice: 3590000,
      packageSessions: 10,
      priceType: 'package',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Triệt Lông',
      isActive: true,
    },
    {
      name: 'Triệt Lông',
      zone: 'Full Body',
      description: 'Triệt lông toàn thân, trọn gói tiết kiệm nhất.',
      singlePrice: 1799000,
      packagePrice: 13999000,
      packageSessions: 10,
      priceType: 'package',
      duration: '120 phút',
      durationMinutes: 120,
      category: 'Triệt Lông',
      isActive: true,
    },

    // ════════════════════════════════════════════════════════
    // GỘI ĐẦU DƯỠNG SINH — 4 combo
    // ════════════════════════════════════════════════════════
    {
      name: 'Gội Đầu Dưỡng Sinh - Combo 1',
      description: 'Combo gội đầu dưỡng sinh cơ bản 7 bước, thư giãn nhẹ nhàng.',
      singlePrice: 79000,
      priceType: 'single',
      duration: '35 phút',
      durationMinutes: 35,
      category: 'Gội Đầu Dưỡng Sinh',
      stepsCount: 7,
      steps: [
        'Khai thông kinh lạc',
        'Tẩy trang rửa mặt',
        'Gội 2 nước',
        'Ủ sả tóc (massage đầu)',
        'Massage CVG ngửa',
        'Sấy tóc',
        'Máy massage chân',
      ],
      isActive: true,
    },
    {
      name: 'Gội Đầu Dưỡng Sinh - Combo 2',
      description: 'Combo gội đầu 11 bước, kết hợp massage mặt nâng cơ và ngâm chân thảo dược.',
      singlePrice: 179000,
      priceType: 'single',
      duration: '55 phút',
      durationMinutes: 55,
      category: 'Gội Đầu Dưỡng Sinh',
      stepsCount: 11,
      steps: [
        'Khai thông kinh lạc',
        'Tẩy trang rửa mặt',
        'Massages mặt nâng cơ',
        'Đắp mặt nạ',
        'Gội 2 nước',
        'Ủ sả tóc (massage đầu)',
        'Ngâm chân thảo dược',
        'Massage CVG tay',
        'Xông nền tai',
        'Sấy tóc',
        'Máy massage chân',
      ],
      isActive: true,
    },
    {
      name: 'Gội Đầu Dưỡng Sinh - Combo 3',
      description: 'Combo gội đầu cao cấp 10 bước, thêm tẩy tế bào chết da mặt và massage CVG toàn diện.',
      singlePrice: 229000,
      priceType: 'single',
      duration: '70 phút',
      durationMinutes: 70,
      category: 'Gội Đầu Dưỡng Sinh',
      stepsCount: 10,
      steps: [
        'Khai thông kinh lạc',
        'Tẩy trang rửa mặt',
        'Tẩy tế bào chết da mặt',
        'Massage mặt chuyên sâu',
        'Đắp mặt nạ',
        'Massage CVG-tay-chân up',
        'Gội 2 nước',
        'Ủ sả tóc (massage đầu)',
        'Sấy tóc',
        'Máy massage chân',
      ],
      isActive: true,
    },
    {
      name: 'Gội Đầu Dưỡng Sinh - Combo 4',
      description: 'Combo gội đầu VIP 11 bước, bao gồm massage đá ngọc thạch và rửa bọt tai.',
      singlePrice: 329000,
      priceType: 'single',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Gội Đầu Dưỡng Sinh',
      stepsCount: 11,
      steps: [
        'Khai thông kinh lạc',
        'Tẩy trang rửa mặt',
        'Tẩy tế bào chết da mặt',
        'Massage mặt chuyên sâu (đá ngọc thạch)',
        'Đắp mặt nạ',
        'Massage CVG-tay-chân up',
        'Gội 2 nước',
        'Ủ sả tóc (massage đầu)',
        'Rửa bọt tai (massage tai)',
        'Sấy tóc',
        'Máy massage chân',
      ],
      isActive: true,
    },

    // ════════════════════════════════════════════════════════
    // DESIGN (Nail Art) — 10 dịch vụ
    // ════════════════════════════════════════════════════════
    {
      name: 'Sơn phủ trang trí',
      description: 'Sơn phủ bóng bảo vệ lớp trang trí nail, giữ màu bền lâu.',
      singlePrice: 10000,
      priceType: 'single',
      duration: '10 phút',
      durationMinutes: 10,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Vẽ gel',
      description: 'Vẽ gel nghệ thuật trên móng, tạo hoa văn, họa tiết tinh tế.',
      priceRangeMin: 5000,
      priceRangeMax: 50000,
      priceType: 'range',
      duration: '15-30 phút',
      durationMinutes: 30,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Vẽ nổi',
      description: 'Vẽ nổi 3D trên móng, tạo hiệu ứng hoa, lá, hình nghệ thuật nổi bật.',
      priceRangeMin: 20000,
      priceRangeMax: 40000,
      priceType: 'range',
      duration: '20-30 phút',
      durationMinutes: 30,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'French đầu móng',
      description: 'Vẽ French tip cổ điển hoặc biến tấu trên đầu móng.',
      priceRangeMin: 10000,
      priceRangeMax: 20000,
      priceType: 'range',
      duration: '15-20 phút',
      durationMinutes: 20,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Ombre, loang, tráng gương',
      description: 'Kỹ thuật ombre chuyển màu, loang nghệ thuật hoặc tráng gương bóng sáng trên móng.',
      priceRangeMin: 15000,
      priceRangeMax: 30000,
      priceType: 'range',
      duration: '20-30 phút',
      durationMinutes: 30,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Ấn xà cừ, hoa khô, kim tuyến',
      description: 'Đắp phụ kiện xà cừ, hoa khô, kim tuyến lên móng tạo điểm nhấn.',
      priceRangeMin: 20000,
      priceRangeMax: 50000,
      priceType: 'range',
      duration: '15-20 phút',
      durationMinutes: 20,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Sticker',
      description: 'Dán sticker trang trí móng với nhiều mẫu mã đa dạng.',
      priceRangeMin: 10000,
      priceRangeMax: 30000,
      priceType: 'range',
      duration: '10 phút',
      durationMinutes: 10,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Bình đá',
      description: 'Đính bình đá (rhinestone) trang trí móng tạo vẻ sang trọng, lấp lánh.',
      priceRangeMin: 10000,
      priceRangeMax: 30000,
      priceType: 'range',
      duration: '15-30 phút',
      durationMinutes: 30,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Phụ kiện nhỏ',
      description: 'Gắn phụ kiện nhỏ trang trí móng.',
      priceRangeMin: 5000,
      priceRangeMax: 15000,
      priceType: 'range',
      duration: '10-20 phút',
      durationMinutes: 20,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },
    {
      name: 'Vẽ theo yêu cầu',
      description: 'Vẽ nail theo yêu cầu riêng của khách. Vui lòng liên hệ trước, giá phụ thuộc chi tiết hình vẽ.',
      priceType: 'custom',
      duration: '30-60 phút',
      durationMinutes: 60,
      category: 'Design',
      hasCustomDesign: true,
      isActive: true,
    },

    // ════════════════════════════════════════════════════════
    // EYE LASH (Nối Mi) — 12 dịch vụ
    // ════════════════════════════════════════════════════════
    {
      name: 'Nối mi classic',
      description: 'Nối mi classic 1:1 tự nhiên, phù hợp với mọi phong cách.',
      singlePrice: 300000,
      priceType: 'single',
      duration: '60-90 phút',
      durationMinutes: 90,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi volume',
      description: 'Nối mi volume dày, bồng bềnh, tạo đôi mắt cuốn hút.',
      priceRangeMin: 250000,
      priceRangeMax: 350000,
      priceType: 'range',
      duration: '90-120 phút',
      durationMinutes: 120,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi Katun',
      description: 'Nối mi Katun (cotton) mềm mại, nhẹ nhàng, giữ lâu.',
      priceRangeMin: 250000,
      priceRangeMax: 350000,
      priceType: 'range',
      duration: '90-120 phút',
      durationMinutes: 120,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi Ani me baby',
      description: 'Nối mi Anime baby tự nhiên, nhẹ nhàng, phong cách trẻ trung.',
      singlePrice: 250000,
      priceType: 'single',
      duration: '60-90 phút',
      durationMinutes: 90,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi đuôi cá',
      description: 'Nối mi đuôi cá tạo hiệu ứng mắt cáo, quyến rũ và cá tính.',
      singlePrice: 250000,
      priceType: 'single',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi thiết kế',
      description: 'Nối mi thiết kế theo yêu cầu, tạo kiểu mắt riêng biệt độc đáo.',
      singlePrice: 350000,
      priceType: 'single',
      duration: '90-120 phút',
      durationMinutes: 120,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi lông chồn',
      description: 'Nối mi lông chồn cao cấp, mềm mại, bền đẹp tự nhiên.',
      singlePrice: 350000,
      priceType: 'single',
      duration: '90-120 phút',
      durationMinutes: 120,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Mí nâu',
      description: 'Nối mi màu nâu tự nhiên, tạo phong cách nhẹ nhàng và sang trọng.',
      priceRangeMin: 230000,
      priceRangeMax: 350000,
      priceType: 'range',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Tháo mi',
      description: 'Tháo mi nối an toàn, nhẹ nhàng không làm hỏng mi thật.',
      singlePrice: 40000,
      priceType: 'single',
      duration: '20-30 phút',
      durationMinutes: 30,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Uốn mi',
      description: 'Uốn mi cong tự nhiên, giúp mắt to tròn và cuốn hút hơn.',
      singlePrice: 200000,
      priceType: 'single',
      duration: '30-45 phút',
      durationMinutes: 45,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Nối mi dưới',
      description: 'Nối mi dưới tạo đôi mắt búp bê, thêm chiều sâu cho ánh nhìn.',
      priceRangeMin: 50000,
      priceRangeMax: 100000,
      priceType: 'range',
      duration: '45-60 phút',
      durationMinutes: 60,
      category: 'Eye Lash',
      isActive: true,
    },
    {
      name: 'Mix mi màu',
      description: 'Mix kết hợp mi nhiều màu sắc đa dạng, tạo điểm nhấn cho đôi mắt.',
      priceRangeMin: 30000,
      priceRangeMax: 100000,
      priceType: 'range',
      duration: '90-120 phút',
      durationMinutes: 120,
      category: 'Eye Lash',
      isActive: true,
    },

    // ════════════════════════════════════════════════════════
    // DỊCH VỤ DA — 3 dịch vụ (giữ nguyên 200k)
    // ════════════════════════════════════════════════════════
    {
      name: 'Hút chì thải độc',
      description: 'Hút chì thải độc da mặt, giúp da sáng mịn, loại bỏ độc tố tích tụ.',
      singlePrice: 200000,
      priceType: 'single',
      duration: '45 phút',
      durationMinutes: 45,
      category: 'Dịch Vụ Da',
      isActive: true,
    },
    {
      name: 'Cấy tinh chất',
      description: 'Cấy tinh chất dưỡng chất vào da, giúp da hấp thu tốt hơn và căng mịn.',
      singlePrice: 200000,
      priceType: 'single',
      duration: '45 phút',
      durationMinutes: 45,
      category: 'Dịch Vụ Da',
      isActive: true,
    },
    {
      name: 'Cấy tảo, collagen, phấn',
      description: 'Cấy tảo xoắn, collagen và phấn vào da, giúp da căng mịn và trẻ hóa.',
      singlePrice: 200000,
      priceType: 'single',
      duration: '45 phút',
      durationMinutes: 45,
      category: 'Dịch Vụ Da',
      isActive: true,
    },

    // ════════════════════════════════════════════════════════
    // DỊCH VỤ LẺ — 14 dịch vụ (Mua 5 tặng 1)
    // ════════════════════════════════════════════════════════
    {
      name: 'Tắm trắng máy hấp',
      description: 'Tắm trắng toàn thân bằng máy hấp chuyên dụng, giúp da trắng sáng đều màu.',
      singlePrice: 450000,
      priceType: 'single',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Bấm tán nhờn, nổi ruồi',
      description: 'Bấm tán nhờn và nổi ruồi trên da, giúp da thông thoáng.',
      singlePrice: 35000,
      priceType: 'single',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Tẩy tế bào chết da đầu',
      description: 'Tẩy tế bào chết da đầu, giúp da đầu sạch gàu, thông thoáng và khỏe mạnh.',
      singlePrice: 35000,
      priceType: 'single',
      duration: '15 phút',
      durationMinutes: 15,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Xông nền tai',
      description: 'Xông nền tai (xông tiên tai) thảo dược, giúp thư giãn và thải độc hiệu quả.',
      singlePrice: 35000,
      priceType: 'single',
      duration: '15 phút',
      durationMinutes: 15,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Massage mặt chuyên sâu nâng cơ',
      description: 'Massage mặt chuyên sâu nâng cơ, giúp da săn chắc và trẻ trung hơn.',
      singlePrice: 99000,
      priceType: 'single',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Massage body 30 phút',
      description: 'Massage toàn thân 30 phút, thư giãn cơ bắp và tăng tuần hoàn máu.',
      singlePrice: 189000,
      priceType: 'single',
      duration: '30 phút',
      durationMinutes: 30,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Massage body 60 phút',
      description: 'Massage toàn thân 60 phút, thư giãn sâu cơ bắp và giảm căng thẳng.',
      singlePrice: 350000,
      priceType: 'single',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Massage body 90 phút',
      description: 'Massage toàn thân 90 phút cao cấp, trọn vẹn thư giãn và phục hồi năng lượng.',
      singlePrice: 499000,
      priceType: 'single',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Đá ngọc thạch',
      description: 'Phụ thu đá ngọc thạch khi kết hợp với dịch vụ massage, tăng hiệu quả thư giãn.',
      singlePrice: 40000,
      priceType: 'single',
      duration: '— (phụ thu)',
      durationMinutes: 0,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Đá nóng',
      description: 'Phụ thu đá nóng khi kết hợp với dịch vụ massage, giúp thư giãn cơ bắp sâu hơn.',
      singlePrice: 40000,
      priceType: 'single',
      duration: '— (phụ thu)',
      durationMinutes: 0,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Ngâm chân thảo dược + massage chân',
      description: 'Ngâm chân thảo dược kết hợp massage chân 90 phút, giúp lưu thông máu và thư giãn toàn thân.',
      singlePrice: 40000,
      priceType: 'single',
      duration: '90 phút',
      durationMinutes: 90,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Chà gót chân + massage chân',
      description: 'Chà gót chân loại bỏ da chết kết hợp massage chân thư giãn.',
      singlePrice: 200000,
      priceType: 'single',
      duration: '40 phút',
      durationMinutes: 40,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Máy thải độc trị đau chân',
      description: 'Sử dụng máy thải độc chuyên dụng giúp giảm đau chân, thải độc tố qua bàn chân.',
      singlePrice: 60000,
      priceType: 'single',
      duration: '60 phút',
      durationMinutes: 60,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
    {
      name: 'Các loại mặt nạ',
      description: 'Đắp mặt nạ dưỡng da với nhiều loại: collagen, hyaluronic, trà xanh, than hoạt tính...',
      singlePrice: 30000,
      priceType: 'single',
      duration: '20 phút',
      durationMinutes: 20,
      category: 'Dịch Vụ Lẻ',
      isActive: true,
    },
  ];

  // Save all new services
  let count = 0;
  for (const svc of newServices) {
    await serviceRepo.save(serviceRepo.create(svc));
    count++;
  }

  console.log(`  ✅ Đã thêm ${count} dịch vụ mới`);
  console.log('\n📊 Tổng kết:');
  console.log('   - Chăm Sóc Da: 8 DV (7 mới + 1 cũ 349k)');
  console.log('   - Triệt Lông: 11 vùng');
  console.log('   - Gội Đầu Dưỡng Sinh: 4 combos');
  console.log('   - Design (Nail Art): 10 DV');
  console.log('   - Eye Lash: 12 DV');
  console.log('   - Dịch Vụ Da: 3 DV');
  console.log('   - Dịch Vụ Lẻ: 14 DV');
  console.log('   ❌ Đã xóa: Nail - Gel Polish, Nail Extension');
  console.log('\n✅ [seed-001] Cập nhật bảng giá dịch vụ hoàn tất!');
};
